config/routes.rb
Rails.application.routes.draw do
  mount DceLti::Engine => "/lti" 

  root :to => 'courses#slash'   # for catching the original post
 
#  get 'courses/show'
  get 'courses/previous_select' => 'courses#previous_select' # just creates the select/options
  get 'courses/previous' => 'courses#previous'  # displays the reserves for that previous instance

  post 'courses/delete'

#  get 'reserves/show'

#  get 'reserves/edit'

#  get 'reserves/index'

#  get 'reserves/show'

  resources :courses , except: [:create, :new, :destroy, :index]
  resources :reserves

  post 'courses/reorder' => 'courses#reorder'
  post 'courses/reuse' => 'courses#reuse'
  get 'presto/:type/' => 'reserves#fetch_cite', :defaults => {:format => :json}



  # Example resource route (maps HTTP verbs to controller actions automatically):
  #   resources :products

  # Example resource route with options:
  #   resources :products do
  #     member do
  #       get 'short'
  #       post 'toggle'
  #     end
  #
  #     collection do
  #       get 'sold'
  #     end
  #   end

  # Example resource route with sub-resources:
  #   resources :products do
  #     resources :comments, :sales
  #     resource :seller
  #   end

  # Example resource route with more complex sub-resources:
  #   resources :products do
  #     resources :comments
  #     resources :sales do
  #       get 'recent', on: :collection
  #     end
  #   end

  # Example resource route with concerns:
  #   concern :toggleable do
  #     post 'toggle'
  #   end
  #   resources :posts, concerns: :toggleable
  #   resources :photos, concerns: :toggleable

  # Example resource route within a namespace:
  #   namespace :admin do
  #     # Directs /admin/products/* to Admin::ProductsController
  #     # (app/controllers/admin/products_controller.rb)
  #     resources :products
  #   end
end

app/controllers/reserves_controller.rb
class ReservesController < ApplicationController
  def show
    resp = Rlist.new.reserve(params[:id])
    @reserve = Reserve.new(JSON.parse(resp.body))
    @course_id = params[:course_id] || @reserve.instance_id
    layout = false;
    if params[:layout]
      layout = true
    end
    if !params[:student]
      @history = fetch_history(params[:id])
    else
      @history = {}
    end
    render :action => "show", :layout => layout
  end
  
  def new
    @course_id = params[:course_id] ||  params[:reserve]["instance_id"]
    if !can_edit?(current_user, @course_id)
      flash[:error]="At this time, you are not authorized to add a Reserve to this course"
      redirect_to '/courses/' +  @course_id and return 
    end
# get library list (libs), default library (lib_def) here
    @libs = Library::library_options
    @material_types = Reserve.material_types
    instructor = current_user.lis_person_sourcedid || ENV['HUID'] # we'll get this when we hook up with LTI
    course_lib = Rlist.new.course_library(@course_id)
    lib = course_lib.empty? ? "" : course_lib['libraryCode']
    @reserve = Reserve.new({:instance_id => @course_id, :contact_instructor_id => instructor, :library_code => lib})
  end

  def create
    if params[:reserve][:instance_id].blank?
      params[:reserve][:instance_id] = params[:course_id]
    end
     if !can_edit?(current_user,  params[:reserve][:instance_id])
      flash[:error]="At this time, you are not authorized to add a Reserve to this course"
      redirect_to '/courses/' +  params[:reserve]["instance_id"] and return
    end
    params[:reserve][:lecture_date] =  params[:iso_date] if !params[:iso_date].blank?
    @reserve = Reserve.new(params[:reserve])
    if !@reserve.valid?
      flash.now[:error] = @reserve.errors[:base] if @reserve.errors[:base]
      @libs = Library::library_options
      @material_types = Reserve.material_types
      @course_id = params[:course_id]
      render "new"
      return
    else
      begin
        redir = ''
        options = {}
        Reserve::FIELDS.each do |k|
          v = @reserve.send(k)
          if !v.blank?
            options[k.to_s.camelize(first_letter =:lower)] = v
          end
        end
        if !options["inputHollisSystemNumber"].blank?
          options["inputHollisSystemNumber"] = options["inputHollisSystemNumber"].split("-")[0]
        end
        options["lectureDate"] = params[:iso_date]  if !params[:iso_date].blank?
        options["submittingSystem"] = "CANVAS"
        options["estimatedEnrollment"] ="0" if @reserve.estimated_enrollment.blank?
        resp = Rlist.new.create(params[:course_id], options)
        log_post(params[:course_id],"","CREATE")
        ""
      rescue StandardError  => bang
        flash[:error] = "Unable to create new Reserve #{params["title"]} : #{bang}"
        @libs = Library::library_options
        @material_types = Reserve.material_types
        @course_id = params[:course_id]
        render "new"
        return
      else
        flash[:success] = "Created new Reserve #{params["title"]} "
        redirect_to '/courses/' +  params[:reserve]["instance_id"] + '/edit'
      end
    end
  end

  def update
    if !can_edit?(current_user,  params[:reserve]["instance_id"])
      flash[:error]="At this time, you are not authorized to update  a Reserve to this course"
      redirect_to '/courses/' +  params[:reserve]["instance_id"] and return
    end
    begin
      err_str = ""
      changed = false
      %w{estimated_enrollment student_annotation lecture_date required visibility}.each do |v| 
        changed = true if params["o_" + v] != params[:reserve][v.to_sym] 
      end
      flash[:info] = "No values were changed" if !changed
      redir = '/reserves/' + params[:reserve]["citation_request_id"] + '/edit?course_id=' + params[:reserve]["instance_id"] if flash[:info] || flash[:error]

# OK, here's where we try to POST.  Note: camelCase for Java!
      if !redir
        begin
          options = {
            estimatedEnrollment:  params[:reserve][:estimated_enrollment],
            studentAnnotation:  params[:reserve][:student_annotation],
            lectureDate:  params[:iso_date],
            required:   params[:reserve][:required],
            visibility:   params[:reserve][:visibility],
            submittingSystem: "CANVAS"
          }
          resp = Rlist.new.update(params[:reserve]["instance_id"],params[:id], options)
          log_post(params[:reserve]["instance_id"],params[:id],"UPDATE")
          ""
        rescue StandardError  => bang
          flash[:error] = "Unable to update Reserve #{params["title"]} : #{bang}"
          redir = '/reserves/' + params[:id] + '/edit?course_id=' + params[:reserve]["instance_id"]
        else
          flash[:success] = "Updated Reserve #{params["title"]} (#{params[:reserve]["citation_request_id"]})"
          redir = '/courses/' +  params[:reserve]["instance_id"] + '/edit'
        end
      end        
      redirect_to redir
    end
  end

  def edit
    if !can_edit?(current_user, params[:course_id])
      flash[:error]="At this time, you are not authorized to update a Reserve to this course"
      redirect_to '/courses/' +  params[:course_id] and return
    end
    # error handling coming soon: check for id, course_id match, etc.
    begin
      resp = Rlist.new.reserve(params[:id])
      @reserve  = Reserve.new(JSON.parse(resp.body))
    rescue StandardError => bang
      flash[:error] = "Unable to retrieve information on this Reserve (ID #{params[:id]}): #{bang}"
      redirect_to  '/courses/' + params[:course_id] + '/edit'
    else
      @reserve
    end
  end

  def index
  end


 # AJAX
  def fetch_cite
    cite = {}
    results = {}
    type = params["type"]
    id = params[:id]
    begin
      if (type == "journal")
        cite = LibServices.new.journal_cite(id)
        Reserve::NEW_FIELDS.each do |field|
          results["reserve_input_#{field['name']}"] = cite[field['name']] if cite[field['name']] && (field["journal"].nil? || field["journal"])
        end
      elsif (type == "hollis")
        cite = LibServices.new.hollis_cite(id)
        Reserve::NEW_FIELDS.each do |field|
          results["reserve_input_#{field['name']}"] = cite[field['name']] if cite[field['name']] && !field["journal"]
        end
      end
      cite['status'] = "Item not found" if !cite['status'] || cite['status'] == 404
      results['status'] = cite['status']
      render :json => results.as_json
    end
  rescue RuntimeError => bang
    cite["status"] = bang
    render :json => cite.as_json(:except => "mods_date")
  end

  def fetch_history(id) 
      resp = Rlist.new.history(id)
      hist = JSON.parse(resp.body)
  end

end

app/helpers/reserves_helper.rb
module ReservesHelper
end

app/views/reserves/_chapter_auth_title.html.erb
<%# handles the messiness of the author, title, in a chapter,  etc. %>
<span class="author"><%= reserve.chapter_author %></span>
<span class="title"><%= reserve.chapter_title %></span>
   <span class="sort_title"><%= reserve.sort_title %> </span>
<% if full %> 
<%= render partial: 'reserves/chapter_collapse',  locals: {:reserve => reserve}  %>
<% end %>

app/views/reserves/_common_inputs.html.erb
<%# these fields are editable, so used by both New and Edit %>
<input type="hidden" id="iso_date" name="iso_date" value="<%=reserve.lecture_date %>"/>
<%= f.input :estimated_enrollment, placeholder: 'Estimated enrollment', required: false %>

<%= f.input :student_annotation, as: :text, placeholder: 'This is displayed to students when they look at the Reading List', label: 'Note to students', required: false  %>
<%= f.input :lecture_date, label: 'Lecture date', required: false, placeholder: 'DD/MM/YYYY',
input_html: { class: 'datepicker' }   %>
<%= f.input :required, label: 'Required Reading', as: :boolean, checked_value: 'Y', unchecked_value: 'N' %>
<%= f.input :visibility, label: 'Visible to Student', as: :boolean, checked_value: 'P', unchecked_value: 'R' %>

app/views/reserves/_display_journal.html.erb
<%# display information we have about a reserve, modulo the editable stuff %>
<% if reserve.author %>
   <span class="author"><%= reserve.author %></span>
 <% else %>
    <span class="author"></span>
<% end %>
<span class="sort_title"><%= reserve.sort_title %></span>
<span class="title"><% if !reserve.title.blank? %>&quot;<%= reserve.title.strip %>&quot;<% end %></span>
<% if full %>
<%= render partial: 'reserves/journal_collapse', locals: {:reserve => reserve} %>
<% end %>

app/views/reserves/_display_non_journal.html.erb
<%# display information we have about a reserve, modulo the editable stuff %>

<% if reserve.chapter? %>
   <%= render partial: 'reserves/chapter_auth_title', locals: {:reserve => reserve, :full => full} %>
<% else %>
    <span class="author"><% if reserve.author %><%= reserve.author %><% elsif reserve.editor %><%= reserve.editor %>, [ed.]<% end %></span>
   <span class="sort_title"><%= reserve.sort_title %> </span>
   <span class="title"><%= reserve.title %><% if reserve.title && !reserve.title.ends_with?('.') %>.<% end %></span>
   <% if reserve.editor && !reserve.author.blank? %>
    <span class="editor"><%= reserve.editor %> [ed.]</span>
   <% end %>
<% if full %>
   <%= reserve.non_journal_info %>
<% end %>
<% end %>

app/views/reserves/_edit_icon.html.erb
<%# isolate the edit and move icons, so we can re-use other partials %>
<span class="edit float-right btn-icon-only" title="Edit <%= reserve.tip_title %>"><a href="<%= edit_reserve_path reserve%>?course_id=<%= reserve.instance_id %>" class="edit_link float-right"><%= icon('pencil') %> </a></span> 
<span class="move float-right btn-icon-only" title="Click and drag to re-order the Reserves list"><%= icon('arrows') %></span>

app/views/reserves/_edit_label.html.erb
  <div class="panel panel-info">
    <div class="panel-heading"><div class="display_lib_info">Library: <% if reserve.library %>
<%= reserve.library.name %> 
<% if reserve.library.contact_email %>
( contact: <a href="mailto:<%= reserve.library.contact_email %>" title="email for questions or problems"><%= reserve.library.contact_email %></a> )
<% end %>
<% else %>
<span class="text-error">NO LIBRARY ASSIGNED!! </span>
<% end %>
<div><span class="status<%='-complete' if reserve.status=='COMPLETE'%> ">(<%= reserve.display_status %>)
<%= icon('check') if reserve.display_status=='Available'%>
</span>

</div>
<div class="res_display">
     <%= render partial: 'reserves/simple_reserve', locals: {:reserve => reserve, :full => full} %>
</div>
</div>
    <div class="panel-body">
      <%= yield %>
    </div>
  </div>

app/views/reserves/_edit_reserve.html.erb
<%= simple_form_for @reserve, url: reserve_path, as: 'reserve', html: { class: 'form-horizontal' },
  wrapper: :horizontal_form,
  wrapper_mappings: {
    check_boxes: :horizontal_radio_and_checkboxes,
    radio_buttons: :horizontal_radio_and_checkboxes,
    file: :horizontal_file_input,
    boolean: :horizontal_boolean
  } do |f| %>
<%= f.error_notification %>
<%= f.input :citation_request_id, as: :hidden %>
<%= f.input :instance_id, as: :hidden%>
<input type="hidden" id="title" name="title" value="<%=reserve.title%>" />
<input type="hidden" id="o_estimated_enrollment" name="o_estimated_enrollment" value="<%=reserve.estimated_enrollment%>" />
<input type="hidden" id="o_student_annotation" name="o_student_annotation" value="<%=reserve.student_annotation %>"/>
<input type="hidden" id="o_lecture_date" name="o_lecture_date" value="<%=reserve.lecture_date %>" />
<input type="hidden" id="o_required" name="o_required" value="<%=reserve.required %>" />
<input type="hidden" id="o_visibility" name="o_visibility" value="<%=reserve.visibility %>" />

<%= render partial: 'common_inputs',  locals: { reserve: @reserve, f: f} %>
<div class="form-group" style="text-align: center;">
<%= f.button :submit, class: "btn btn-submit" %>
</div>

<% end %>

app/views/reserves/_journal_collapse.html.erb
in <%= reserve.journal_title %>
<%= reserve.journal_info %>
<% if reserve.issn %>ISSN: <%= reserve.issn %><% end %>

app/views/reserves/_reserve_status.html.erb
<%# simple presentation of a single reserve  statuses, editability  %>
<% if params[:viewonly].to_s != "true" %>
<span class="visibility"><%= reserve.visibility == "R" ? "Not Visible" : "Visible" %></span>
<% end %>

<% if reserve.required == "Y" %>
<span class="status-required" >required</span>
<% else %>
<span class="status-required" style="display:none">zzz</span>
<% end %>
<% cl = "status"
   stat = reserve.display_status
   if stat == "Reuse" && (params[:layout].to_s != "true" ||  params[:viewonly].to_s == "true")
#   if params[:viewonly].to_s == "true" && stat == "Reuse"
      stat = "Coming Soon"
   end
   if stat == "Available" 
      cl = cl + "-available"
   elsif stat == "Coming Soon"
      cl = cl + "-soon"
   end
%>
<span class="<%= cl %>"><%= stat %></span>

<% if !reserve.lecture_date.blank? || reserve.student_annotation %>
<br/>
<% if !reserve.lecture_date.blank? %>
Lecture Date: <span class="lec_date"><%= Time.parse(reserve.lecture_date).strftime("%b %d, %Y") %></span>
<span class="sortdate"><%= (Time.parse(reserve.lecture_date).to_i/86401) %></span>
<% else %>
<span class="sortdate"></span>
<% end %>
<% if reserve.student_annotation %><span class="note"><%= reserve.student_annotation %></span><% end %>


<% end %>

app/views/reserves/_simple_reserve.html.erb
<%# simple presentation of a single reserve request  %>
<% if reserve.journal? %>
  <%= render partial: 'reserves/display_journal', locals: {:reserve => reserve, :full => full} %>
<% else %>
  <%= render partial: 'reserves/display_non_journal', locals: {:reserve => reserve, :full => full} %>
<% end %>

<% if reserve.dig_url %>
 <span class="urlLink btn-link">
<a href="<%= reserve.dig_url %>" target="dig_link" class="dig_link" title="Read <% if !reserve.title.blank? %> <%= reserve.title %><% end %> online">View Online</a> <%= icon('external-link')%></span> 
<% elsif !reserve.aleph_url.blank? %>
<span class="urlLink btn-link">
<a href="<%= reserve.aleph_url %>" target="dig_link" class="dig_link" 
title="Find out availability of this reserve">HOLLIS link</a> <%= icon('external-link')%></span>
<% end %>

app/views/reserves/edit.html.erb
<%# edit a reserve request 
FIELDS THAT CAN BE MODIFIED:
    Estimated Number of Enrolled Students: 
    Lecture/Class Date: 
    Student View Display: 
    Required Reading: 
Note to Students:

%>
<ol class="breadcrumb">
<li><a href="https://canvas.harvard.edu"><%= icon('home') %></a></li>
<li> <a href="/courses/<%= @reserve.instance_id %>/edit" class="link-icon" title="back to list">Manage <%= ENV['LTI_PROVIDER_TITLE'] %></a></li>
<li class="active">Reserve Request</li>
</ol>


<div class="row row-lti  reserves-edit">

Current Reserve: <span class="libnote dfn">(some bibliographic information may have been edited by library staff)</span>
</div>
<div class="row row-lti lti-section">

<%= render partial: 'edit_reserve', layout: 'edit_label', locals: { :reserve => @reserve, :full => true} %>
</div>

app/views/reserves/index.html.erb
<h1>Reserves#index</h1>
<p>Find me in app/views/reserves/index.html.erb</p>

app/views/reserves/show.html.erb
<ol class="breadcrumb">
<li><a href="https://canvas.harvard.edu"><%= icon('home') %></a></li>
<li> <a href="/courses/<%= @reserve.instance_id %>/edit" class="link-icon" title="back to Course">Manage  <%= ENV['LTI_PROVIDER_TITLE'] %></a></li>
<li class="active">Reserve Request</li>
</ol>

<div>

<%= render  'reserves/simple_reserve', :reserve => @reserve, :full => true %>
<%= render partial: 'reserves/reserve_status', locals: {:reserve => @reserve } %>
<% if !@reserve.aleph_url.blank? %>
 <span class="urlLink btn-link"><a href="<%= @reserve.aleph_url %>" target="aleph_link" title="Link to HOLLIS Classic record">Hollis Link</a><%= icon('external-link')%>
</span>
<% end %>
</div>
<div class="library">

<% if params[:viewonly].to_s == "true" %>
 <span class="urlLink btn-link">
 <a href="http://library.harvard.edu/<%= @reserve.library.library_code.downcase %>" target="library_link" title="Library page">  <%= @reserve.library.name %></a><%= icon('external-link')%>
</span>
<% else %>
<% if @reserve.library.support_url %>
 <span class="urlLink btn-link">
<a href="<%=  @reserve.library.support_url %>" target="library_link" title="Library support page"><%= @reserve.library.name %></a><%= icon('external-link')%>
</span>
<% else %>
<%= @reserve.library.name %>
<% end %>
<% end %>
</div>
<% if params[:viewonly].to_s != "true" %>
<hr/>
<p><big>Original <%= @reserve.input_citation_type %> request</big></p>


<dl class="dl-horizontal">


<% Reserve::NEW_FIELDS.each do |f| %>
<% inp = "input_#{f['name']}".to_sym
   next if @reserve.input_citation_type == "NON_JOURNAL" && !f["journal"].blank? && f["journal"]
   next if @reserve.input_citation_type == "JOURNAL" && (f["journal"].blank? || !f["journal"])
   value = @reserve.send(inp)
   if (value) %>
<dt><%= f["label"] %>:</dt> <dd><%= value %></dd>
  <% end %>
<% end %>
<dt>Note to Reserves</dt>
<dd>
<%= @reserve.instructor_note || "(none)" %> 
</dd>
</dl>

<% if !@history.blank? %>
<hr/>
<div class="table-responsive">
<table class="table table-hover table-condensed">
<caption><big><bold>Request History</bold></big></caption>
<thead>
<tr><th>Date</th><th>Status</th><th>Note</th></tr>
</thead>
<tbody>
<% @history.each do |h| %>
<tr><th><%= Time.parse(h["date"]).strftime "%d %B %Y %H:%M" %></th>
<th><%= h["status"] %></th>
<th><%= h["note"] %></th>
</tr>
<% end %>
</tbody>
</table>
</div>
<% end %>
<% end %>

app/views/reserves/update.html.erb
<%= @reserve %>