config/routes.rb
Rails.application.routes.draw do
  mount DceLti::Engine => "/lti" 

  root :to => 'courses#slash'   # for catching the original post
 
#  get 'courses/show'
  get 'courses/previous_select' => 'courses#previous_select' # just creates the select/options
  get 'courses/previous' => 'courses#previous'  # displays the reserves for that previous instance

  post 'courses/delete'

#  get 'reserves/show'

#  get 'reserves/edit'

#  get 'reserves/index'

#  get 'reserves/show'

  resources :courses , except: [:create, :new, :destroy, :index]
  resources :reserves

  post 'courses/reorder' => 'courses#reorder'
  post 'courses/reuse' => 'courses#reuse'
  get 'presto/:type/' => 'reserves#fetch_cite', :defaults => {:format => :json}



  # Example resource route (maps HTTP verbs to controller actions automatically):
  #   resources :products

  # Example resource route with options:
  #   resources :products do
  #     member do
  #       get 'short'
  #       post 'toggle'
  #     end
  #
  #     collection do
  #       get 'sold'
  #     end
  #   end

  # Example resource route with sub-resources:
  #   resources :products do
  #     resources :comments, :sales
  #     resource :seller
  #   end

  # Example resource route with more complex sub-resources:
  #   resources :products do
  #     resources :comments
  #     resources :sales do
  #       get 'recent', on: :collection
  #     end
  #   end

  # Example resource route with concerns:
  #   concern :toggleable do
  #     post 'toggle'
  #   end
  #   resources :posts, concerns: :toggleable
  #   resources :photos, concerns: :toggleable

  # Example resource route within a namespace:
  #   namespace :admin do
  #     # Directs /admin/products/* to Admin::ProductsController
  #     # (app/controllers/admin/products_controller.rb)
  #     resources :products
  #   end
end

app/controllers/courses_controller.rb
class CoursesController < ApplicationController
  def show
    begin
      params[:viewonly] = "true"
      c  = Course.new(params[:id])
      @reserves = c.student_list
    rescue Exception => bang
      bangmsg = bang.to_s
      if bangmsg.include? "404 - Not Found"
        bangmsg = "Course instance does not exist in the Reserves Tool database"
      end
      flash[:error] = "Unable to retrieve information on Course Instance #{params[:id]}: #{bangmsg}"
    end
    begin
      @instance = fetch_info(params[:id])
    rescue StandardError => bang
      flash[:notice] = "Unable to retrieve Course details: #{bang}"
    end
  end

  def edit
    redirect_to :action => :show, id: params[:id] and return if !can_edit?(current_user, params[:id])
    begin
      c  = Course.new(params[:id])
      @reserves = c.list
    rescue Exception => bang
      bangmsg = bang.to_s
      if bangmsg.include? "404 - Not Found"
        bangmsg = "Course instance does not exist in the Reserves Tool database"
      end
      flash[:error] = "Unable to retrieve information on Course Instance #{params[:id]}: #{bangmsg}"
    end
    begin
      @instance = fetch_info(params[:id])
      @others = fetch_others(@instance)
    rescue StandardError => bang
      flash[:notice] = "Unable to retrieve information on previous Instances: #{bang}"
    end
    rescue StandardError => bang
      flash[:notice] = "Unable to retrieve Course details: #{bang}"
  end
  def previous
    begin
      # do all the good grabbing of reserves
      c =  Course.new(params[:prev_id])
      c.list
      c.author_sort
      prev_reserves = c.reserves
      json = Rlist.new.course_library(params[:id])
      lib_code = json['libraryCode']
      if lib_code.blank? && prev_reserves.length > 0 
        lib_code = prev_reserves[0].library_code
      end
    rescue StandardError => bang
      flash[:error] = "Unable to retrieve information on the previous course #{params[:id]}: #{bang}"
      redirect_to  :action => :edit, id: params[:id] and return
    end
    respond_to do |format|
      format.html do
        render :partial => 'courses/previous',
        :locals => {:prev_reserves => prev_reserves, :id => params[:id], :lib_code => lib_code, :course_title => params[:course_title] }
      end
    end
  end
  def previous_select
    begin
      others = fetch_others(params[:prev_id])
    rescue Exception => bang
      flash[:error] = "Unable to retrieve information from iCommons on Course Instance #{params[:id]}: #{bang}"
       redirect_to  :action => :edit, id: params[:id]
    end
    respond_to do |format|
      format.html do
        render :partial => 'courses/select_previous',
        :locals => { :others => others, :id => params[:id]}
      end
    end
  end
  def reuse
    redirect_to :action => :show, id: params[:id] and return if !can_edit?(current_user, params[:id])
    # here's where all the re-usability magic happens!
    count = 0
    errs = []
    opts = {}
    opts["submittingSystem"] = "CANVAS"
    opts["estimatedEnrollment"] ="0"
    opts["contactInstructorId"] = current_user.lis_person_sourcedid || ENV['HUID'] # we'll get this when we hook up with LTI
    opts["contactInstructorIdType"] = "HUID"
    opts["instanceId"] = params[:id]
    opts["visibility"] = "P"
    opts["status"]= "REUSE"
    if params[:reuse_ids]
      params[:reuse_ids].each do |reuse_id|
        ret_str = reuse_one(opts, reuse_id)
        if ret_str.empty?
          count = count + 1
        else
          errs.push(ret_str)
        end
      end
    end
#    @reserves = Course.new(params[:id]).list
    flash[:notice] = "#{count} reserve#{'s' if count != 1} re-used"
    flash[:error] = errs if !errs.blank?
    redirect_to :action => :edit, id: params[:id] and return
  end
  def reuse_one(opts, reuse_id) 
    begin
      resp = Rlist.new.reserve(reuse_id)
      reuse_reserve = JSON.parse(resp.body)
      reuse_reserve.each do |k, v|
        if k.is_a?(String) && k.starts_with?("input")
          if !v.blank?
            opts[k] = v
          end
        end
      end
      opts["libraryCode"]  = reuse_reserve["libraryCode"]
      opts["citationId"] = reuse_reserve["citationId"]
      opts["required"] = reuse_reserve["required"]
      @reserve = Reserve.new(opts)
      if !@reserve.valid?
        errors = "Unable to create new Reserve from previous_reserve_id #{reuse_id}: #{errmessage(@reserve.errors.messages)}" if !@reserve.errors.messages.blank?
      else
        resp = Rlist.new.create(opts["instanceId"],opts)
        log_post(opts["instanceId"],reuse_id,"REUSE")
        ""
      end
    end
  rescue StandardError  => bang
    "Unable to create new Reserve from  previous_reserve_id #{reuse_id}: #{bang}"
  end
  def delete_one(id, res_id)
    redirect_to :action => :show, id: params[:id] and return if !can_edit?(current_user, params[:id])
    begin
      Rlist.new.delete(params[:id], res_id)
      log_post(params[:id], res_id, "DELETE")
      ""
    end
  rescue StandardError => bang
    "#Reserve ID #{res_id} failed: #{bang}; "
  end
  def delete
    redirect_to :action => :show, id: params[:id] and return if !can_edit?(current_user, params[:id])
    count = 0
    err_str = ""
    if params[:res_ids]
      params[:res_ids].each do |res_id|
        ret_str = delete_one(params[:id], res_id)
        if ret_str.empty?
          count = count + 1 
        else
          err_str = "#{err_str}; #{ret_str}"
        end
      end
    end
    @reserves = Course.new(params[:id]).list
    flash[:notice] = "#{count} reserve#{'s' if count != 1} deleted"
    flash[:error] = err_str if !err_str.empty?
    redirect_to :action => :edit, id: params[:id]
  end
  def reorder
    redirect_to :action => :show, id: params[:id] and return if !can_edit?(current_user, params[:id])
    begin
      resp = Rlist.new.reorder( params[:id], params[:sort_order])
      log_post(params[:id],"#{params[:sort_order]}","REORDER")
      flash[:notice] = "Reserves reordered"
    rescue StandardError => bang
      flash[:error] = bang
    end
    redirect_to :action => :edit, id: params[:id] 
  end
  def slash
#    flash[:error] = "We got to slash!"
    redirect_to :action => :show, id: session[:lis_course_offering_sourcedid]
  end

# sometime I'll make this private, or a concern, or something!
  def fetch_info(id)
    ii = InstanceInfo.new(id)
  end
  def fetch_others(ii)
    ii.fill_others
    ii.others
  end
# another thing for concerns, eventually
  def errmessage(messages)
    errs = ""
    messages.each do |k,v|
      if !v.blank?
        errs = "#{errs} #{v.join}"
      end
    end
    errs
  end
end

app/helpers/courses_helper.rb
module CoursesHelper
end

app/views/courses/_previous.html.erb
<%# LOCALS: prev_reserves, id, lib_code, course_title %>

<% if prev_reserves.blank? %>
<strong>No reserves for this <%= course_title %> instance</strong>
<% else %>
<h4><%= course_title %></h4>
<%= form_tag({controller: "courses", action: "reuse"}, method: "post", class: "previous_list") do %>
<%= hidden_field_tag("id", id) %>
<%= hidden_field_tag("lib_code", lib_code) %>

<ul class="list-with-floats">
<li class="head">
<button type="button" class="btn btn-default btn-xs" id="select_all_reuse">
<% if prev_reserves.length > 1 %>
<%= "Select all #{prev_reserves.length} previous Reserves" %>
<% else %>
<%= "Select previous Reserve" %>
<% end %>
</button>
<button type="button" class="btn btn-default btn-xs disabled" id="deselect_all_reuse">Clear selections</button>

 <span class="update" title="Re-use selected reserve(s)"><%=submit_tag(value="Re-use selected reserve(s)", {:class => "btn btn-disabled chks_reuse", :id => "reuse_btn"}) %></span>

</li>
</ul>

<ul class="list-with-floats chk_grp" id="ids_reuse">
  <% prev_reserves.each do |reserve| %>
     <% if !reserve.citation_id.blank? %>
  <li id="<%= reserve.citation_id %>"><%= check_box_tag("reuse_ids[]", "#{reserve.citation_request_id}", false, {:id => "reuse_ids__#{reserve.citation_request_id}", :class => "chk_reuse", :title => "Select #{reserve.tip_title}"}) %>

<%= render partial: 'reserves/simple_reserve', locals: {reserve: reserve, full: false} %></li>
     <% end %>
  <% end %>
</ul>
<% end %>
<script>checkBoxSetup("reuse")</script>
<% end %>

app/views/courses/_select_previous.html.erb
<div id="previous_list" class="float-right">

  <form name="prev_select_form" id="prev_select_form">
     <label for="prev_select">Re-use reserves from: </label>
     <select id="prev_select">
      <% others.each do |ci| %>
    <option value="<%=ci['instance_id'] %>"><%= ci['term'] %></option>
    <% end %>
    </select>
  </form>
</div>

app/views/courses/edit.html.erb
<% if @reserves %>
<h4>Number of reserves: <%= @reserves.count %></h4>
<h4>Manage <%= ENV['LTI_PROVIDER_TITLE'] %> <a href="<%= ENV['DOC_URL'] %>"
title="<%= ENV['LTI_PROVIDER_TITLE'] %> Quick Reference Guide" target="guide_wiki"><%= icon('question-circle') %></a> <div class="float-right">
<a class="link-icon"  href="/courses/<%= params[:id] %>/?viewonly=true">View as Student</a></div></h4>
<div id="newOrReuse" class="float-right"><a href="<%= new_reserve_path  %>?course_id=<%= params[:id] %>" class="link-icon" title="Add New Reserve"><%= icon('plus-circle') %> Add New Reserve</a>

<% if !@others.blank? %>
  <form name="prev_select_form" id="prev_select_form" >
    <label for="prev_select">Re-use reserves from: </label>
    <select id="prev_select"><option value="">Select a previous term</option>
      <% @others.each do |ci| %>
    <option value="<%=ci['instance_id'] %>"><%= ci['term'] %></option>
    <% end %>
    </select>
  </form>

<script>reuseSetup()</script>
<% end %><%# END OF PREVIOUS TERMS %>
</div>
<%= form_tag({controller: "courses", action: "reorder"}, method: "post", class: "reserves-list reorder", id: "form_reorder") do %>
<%= hidden_field_tag("id", params[:id]) %>
<input type="hidden" name="sort_order" id="sort_order" />
</span>

<% end %>

<%= form_tag({controller: "courses", action: "delete"}, method: "post", class: "reserves-list", id: "form_del") do %>
<%= hidden_field_tag("id", params[:id]) %>
<ul class="list-with-floats">
<li class="head">

<span class="delete" title="Remove selected reserve(s)"><input name="reorder"
value="Remove selected reserve(s)" class="btn btn-disabled chks_submit_del_submit submit_btn" id="del_btn" type="button"></span>

<span class="reorder" title="Commit reordering"><input name="reorder"
value="Save new Reserves order" class="btn btn-disabled reorder_submit submit_btn" id="reorder_btn" type="button"></span>
<span class="refresh" title="Restore original order"><input name="restore"
value="Restore original order" class="btn btn-disabled restore_submit" id="restore_btn"
type="button"></span>
</li>

<li class="selDel">
<button type="button" class="btn btn-default btn-xs" id="select_all_del">Select all Reserves</button>
<button type="button" class="btn btn-default btn-xs disabled" id="deselect_all_del">Clear selections</button>

</li>

</ul>
<ul class="list-with-floats chk_grp" id="ids_del">
<% @reserves.each do |reserve| %>
<li id="<%= reserve.citation_request_id %>">
<% if !reserve.display_status.starts_with?("Delet") %>
<%= check_box_tag("res_ids[]", reserve.citation_request_id, false, {:id => "res_ids__#{reserve.citation_request_id}", :class => "chk_del", :title => "Select #{reserve.tip_title}"}) %>
<% end %>
<%= render partial: 'reserves/edit_icon', locals: {:reserve => reserve} %>
<span class="view " title="View  <%= reserve.tip_title %>"><a href="<%= reserve_path reserve%>?layout=true" class="view_link"><%= icon('info-circle') %></span>

<span class="nomove">
<%= render partial: 'reserves/simple_reserve', locals: {:reserve => reserve, :full => false} %>
<%= render partial: 'reserves/reserve_status', locals: {:reserve => reserve} %>
</span> 

</li>
<% end %>
</ul>
<% end %>
<script>checkBoxSetup("del")</script>
<% end %>
<div id="reuse_list" class="previous"></div>

app/views/courses/show.html.erb
<% if @reserves %>

<h3>Number of reserves: <%= @reserves.count %>
<% if can_edit?(current_user, params[:id]) %>
<div class="float-right"><a class="link-icon" href="/courses/<%= params[:id] %>/edit">Manage <%= ENV['LTI_PROVIDER_TITLE'] %></a></div>
<% end %>
</h3>
<div id="reserves-list">
<% if @reserves.count > 2 %>
<input class="search" placeholder="Search" />
<div class="btn-group float-right">
        <button class="sort btn btn-default" data-sort="sort_title">
              Sort by title
            </button>
            <button class="sort btn btn-default" data-sort="author">
              Sort by author
            </button>
           <button class="sort btn btn-default" data-sort="status-required">
              Sort by  <span class="crimson-caps">required</span> status
            </button>
	 <% if Course.list_has_ins_order?(@reserves) %>
	     <button class="sort btn btn-default" data-sort="order">
	       Sort by instructor order
            </button>
         <% end %>
	 <% if Course.list_has_dates?(@reserves) %>
	    <button class="sort btn btn-default" data-sort="sortdate">
              Sort by lecture date
            </button>
	 <% end %>
</div>
<% end %>
<ul class="list-with-floats" id="reserves_ids">
<% @reserves.each do |reserve| %>
<li id="r_<%= reserve.citation_request_id %>">

<span class="view float-left" title="View full details"><a href="#cllps_<%= reserve.citation_request_id %>" class="view_link float-left" role="button" data-toggle="collapse" aria-expanded="false" aria-controls="#cllps_<%= reserve.citation_request_id %>"><%= icon('info-circle') %></span>

<div>
<span class="order"><%= (reserve.instructor_sort_order || '') %></span>
<%= render partial: 'reserves/simple_reserve', locals: {:reserve => reserve, :full => false} %>
<%= render partial: 'reserves/reserve_status', locals: {:reserve => reserve} %>
<span class="library float-right"><a href="http://library.harvard.edu/<%= reserve.library.library_code.downcase %>" 
target="library_link" title="Get information about <%= reserve.library.name %>"><%= reserve.library.name %></a>
<%= icon('external-link')%>
</span>
<div class="collapse" id="cllps_<%= reserve.citation_request_id %>">
  <div class="well">
    <% if reserve.journal? %>
      <%= render partial: 'reserves/journal_collapse', locals: {:reserve => reserve} %>
   <% elsif  reserve.chapter? %>
   <%= render partial: 'reserves/chapter_collapse', locals: {:reserve => reserve} %>
   <% else %>
   <%= reserve.non_journal_info %>
<% end %>

  </div>
</div>
</div> 

</li>
<% end %>
</ul>
</div>
<% end %>
<!-- script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/list.js/1.1.1/list.min.js"></script -->
<script type="text/javascript">

    var options = {
     valueNames: [ 'sort_title' ,'order','author', 'sortdate', 'status-required'],
     listClass: 'list-with-floats'
    };

    var rList = new List('reserves-list', options);
  </script>